config/routes.rb
Rails.application.routes.draw do
  resources :user_books
  resources :users
  resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :user_books
  has_many :users, through: :user_books
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_books
  has_many :books, through: :user_books

  def name
    "#{first_name}" + " #{last_name}"
  end
end

app/models/user_book.rb
class UserBook < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    redirect_to book_path(@book)
  end

  def edit
  end

  def update
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:name, :genre, :author, :synopsis)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  before_action :set_userbook, only: [:show, :edit, :update, :destroy]

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def userbook_params
    params.require(:userbook).permit(:read_status, :review, :rating, :possesion)
  end

  def set_userbook
    @userbook = UserBook.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to user_path(@user)
  end

  def edit
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :password, :email, :user_name)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container">
<br>
<h1 class="text-success">Update Book Info: </h1>
<br>
<div class="text-danger">
  <%= form_for @book do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :genre %>
  <%= f.text_field :genre %>
  <br>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br>
  <%= f.label :synopsis %>
  <%= f.text_area :synopsis %>
  <br>
  <%=  f.submit class: "btn btn-info" %>
  <span class="btn btn-danger"><%= link_to "Delete Book", :method => :delete, :class => "text-white" %></span>
  <span class="btn btn-warning"><%= link_to "Main Menu", books_path, :class => "text-white" %></span>
<% end %>
</div>
</div>

app/views/books/index.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-warning" type="button"><%= link_to "Main Menu", books_path, :class => "text-white" %></button>
    <button class="btn btn-info" type="button"><%= link_to "Users Menu", users_path, :class => "text-white" %></button>
  </form>
</nav>

<div class="container">
  <br>
  <h1 class="text-danger">Books: </h1>
  <br>
  <% @books.each do |book| %>
  <p class="text-danger"><%= link_to book.name, book_path(book), :class => "text-info" %></p>
  <% end %>
  <br>
  <button type="button" class="btn btn-danger"><%= link_to "Add a New Book", new_book_path, :class => "text-white" %></button>
</div>

app/views/books/new.html.erb
<div class="container">
  <br>
  <h1 class="text-success">Add a New Book: </h1>
    <div class="text-danger">
      <%= form_for @book do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :genre %>
      <%= f.text_field :genre %>
      <br>
      <%= f.label :author %>
      <%= f.text_field :author %>
      <br>
      <%= f.label :synopsis %>
      <%= f.text_field :synopsis %>
      <br>
      <%=  f.submit class: "btn btn-info" %>
      <% end %>
    </div>
    <br>
    <div class="btn btn-warning"><%= link_to "Main Menu", books_path %></div>
</div>

app/views/books/show.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-warning" type="button"><%= link_to "Main Menu", books_path, :class => "text-white" %></button>
    <button class="btn btn-info" type="button"><%= link_to "Users Menu", users_path, :class => "text-white" %></button>
  </form>
</nav>

<div class="container">
  <br>
  <h1 class="text-success"><%= @book.name%></h1>
  <br>
  <h4 class="text-success">Owner: </h4>
  <br>
  <% @book.users.each do |user| %>
  <ul>
    <li class="text-success"><%= link_to user.name, user_path(user), :class => "text-info" %></li>
  </ul>
  <% end %>
  <br>
  <h4 class="text-warning">Reviews: </h4>
  <br>
  <% @book.user_books.each do |userbook| %>
    <h5 class="text-info"><%= userbook.user.first_name %></h5>
    <h6 class="text-success">"<%= userbook.review %>"</h6>
    <p class="text-success">Read Status: <%= userbook.read_status %></p>
    <p class="text-success">Rating: <%= userbook.rating %></p>
  <% end %>
  <br>
  <button type="button" class="btn btn-danger"><%= link_to "Edit Book", edit_book_path(@book), :class => "text-white" %></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadMore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_books/index.html.erb
<div class="container">
  <br>
  <h1 class="text-danger">Reviews: </h1>
  <br>
  <% @userbook.each do |userbook| %>
  <p class="text-danger"><%= link_to user.name, user_path(user), :class => "text-info" %></p>
  <% end %>
  <br>
  <button type="button" class="btn btn-warning"><%= link_to "Main Menu", users_path, :class => "text-white" %></button>
  <button type="button" class="btn btn-danger"><%= link_to "Add a New User", new_user_path, :class => "text-white" %></button>
  <button type="button" class="btn btn-info"><%= link_to "Books Menu", books_path, :class => "text-white" %></button>
  <button type="button" class="btn btn-success"><%= link_to "Reviews Menu", user_books_path, :class => "text-white"%></button>
</div>

app/views/users/edit.html.erb
<div class="container">
<br>
<h1 class="text-success">Update User Info: </h1>
<br>
<div class="text-danger">
  <%= form_for @user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <br>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%=  f.submit class: "btn btn-info" %>
  <span class="btn btn-danger"><%= link_to "Delete User", :method => :delete %></span>
  <span class="btn btn-warning"><%= link_to "Main Menu", users_path, :class => "text-white" %></span>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-warning" type="button"><%= link_to "Main Menu", users_path, :class => "text-white" %></button>
    <button class="btn btn-info" type="button"><%= link_to "Books Menu", books_path, :class => "text-white" %></button>
  </form>
</nav>


<div class="container">
  <br>
  <h1 class="text-danger">Users: </h1>
  <br>
  <% @users.each do |user| %>
  <p class="text-danger"><%= link_to user.name, user_path(user), :class => "text-info" %></p>
  <% end %>
  <br>
  <button type="button" class="btn btn-danger"><%= link_to "Add a New User", new_user_path, :class => "text-white" %></button>
</div>

app/views/users/new.html.erb
<div class="container">
  <br>
  <h1 class="text-success">Add a New User: </h1>
    <div class="text-danger">
      <%= form_for @user do |f| %>
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>
      <br>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
      <br>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
      <br>
      <%= f.label :password %>
      <%= f.text_field :password %>
      <br>
      <%= f.label :email %>
      <%= f.text_field :email %>
      <br>
      <%=  f.submit class: "btn btn-info" %>
      <% end %>
    </div>
    <br>
    <div class="btn btn-warning"><%= link_to "Main Menu", users_path %></div>
</div>

app/views/users/show.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <button class="btn btn-warning" type="button"><%= link_to "Main Menu", users_path, :class => "text-white" %></button>
    <button class="btn btn-success" type="button"><%= link_to "Books Menu", books_path, :class => "text-white" %></button>
  </form>
</nav>


<div class="container">
  <br>
  <h1 class="text-success"><%= @user.user_name%></h1>
  <br>
  <p class="text-warning"> Welcome to <%= @user.name %>'s bookshelf! </p>
  <br>
  <h4 class="text-success">Books: </h4>
  <br>
  <% @user.books.each do |book| %>
  <ul>
    <li class="text-success"><%= link_to book.name, book_path(book), :class => "text-info" %></li>
  </ul>
  <% end %>
  <br>
  <button type="button" class="btn btn-danger"><%= link_to "Edit User", edit_user_path(@user), :class => "text-white" %></button>
</div>